version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/html.html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  
